### PR TITLE
Add instrumentation

### PR DESCRIPTION
**Pull request by b20n**

### CODE REVIEW

**Comment by b20n** [comment]
I believe this is ready for review.

**Comment by sagelywizard** [comment]
Looks good. Though there are only a [few types of errors](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes) which are returned by Kafka. Maybe we should have counters for these too?

**Comment by b20n** [comment]
Good idea; done.

**Comment by sagelywizard** [comment]
:+1:

**Pull request merged**
